# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Watch these filename extensions.
include_ext = ["go", "html", "toml"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "vendor", "bin"]
# Exclude specific regular expressions.
exclude_regex = ["_test.go"]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 100 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = "3s" # ms

[log]
# removes log clutter on startup
main_only = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
