version: "3.8"
services:
  postgresql:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data
    restart: always
  nats-server:
      image: nats:latest
      restart: always
      ports:
        - "4222:4222"
  skeleton:
    build: .
    container_name: skeleton
    environment:
      - NATS_URL=nats://0.0.0.0:4222
    depends_on:
      - postgresql
      - nats-server
    ports:
      - "8877:8877"
#  network_mode: host
    restart: always
