version: "3.8"
services:
  postgres:
    container_name: skeleton-postgres
    image: postgres:15.3
    restart: always
    networks:
      skeleton:
    ports:
      - "54329:5432"
    environment:
      - POSTGRES_USER=devbox
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=devbox
    volumes:
      - "postgres15-data:/var/lib/postgresql/data/:rw"
      - "./scripts/backend/db.sh:/home/db.sh"
      - "./db/schema.sql:/home/schema.sql"
    command: postgres #-c 'config_file=/etc/postgresql/postgresql.conf'

  nats:
    image: nats:2.9
    restart: always
    ports:
      - 4222:4222

  pgweb:
    container_name: skeleton-pgweb
    restart: always
    image: sosedoff/pgweb:0.14.1
    command: /usr/bin/pgweb --bind=0.0.0.0 --listen=8081 --url=postgres://devbox@skeleton-postgres:5432/postgres?sslmode=disable
    ports:
      - "8999:8081"
    networks:
      skeleton:
    depends_on:
      - postgres

networks:
  skeleton:
    name: skeleton


volumes:
  postgres15-data:
