name: Pull Request checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
        ports:
          - "5432:5432"
    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout Pull Request HEAD commit instead of the default Pull Request merge commit.
          fetch-depth: 1
      - name: Git safe.directory
        # Fixes following git error:
        #   error obtaining VCS status: exit status 128
        #   Use -buildvcs=false to disable VCS stamping. (typecheck)
        run: git config --global --add safe.directory '*'
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.5"
      - name: Run go tests
        run: |
          go install github.com/mfridman/tparse@latest 
          set -o pipefail && DIR=$PWD go test -parallel 1 ./... -json | tparse -all
      - name: Static analysis check
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/golang-cz/static-analysis:v23.10.15-a16f233
          options: -v ${{ github.workspace }}:/src -w /src
          run: golangci-lint run -c ./.golangci.yml ./...
      - name: Check for big files
        run: |
          if [[ $(git ls-files | xargs du -hs --threshold=2M 2>/dev/null | tee /dev/stderr | wc -l) -gt 0 ]]; then
            echo "Aborting due to big files in the git repository."
            exit 1;
          fi
