name: Pull Request checks
on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
        ports:
          - "5432:5432"
    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout Pull Request HEAD commit instead of the default Pull Request merge commit.
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
      - name: Run go tests
        run: |
          go install github.com/mfridman/tparse@latest 
          set -o pipefail && DIR=$PWD go test -parallel 1 ./... -json | tparse -all
      - name: Static analysis check
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/golang-cz/static-analysis:latest
          options: -v ${{ github.workspace }}:/app
          run: |
            cd /app
            golangci-lint run -c /app/.golangci.yml /app/services/... /app/internal/... /app/pkg/... /app/data/...
      - name: Check for big files
        run: |
          git config --global --add safe.directory '*'
          if [[ $(git ls-files | xargs du -hs --threshold=2M 2>/dev/null | tee /dev/stderr | wc -l) -gt 0 ]]; then
            echo "Aborting due to big files in the git repository."
            exit 1;
          fi
