name: Pull Request checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  jira-card:
    runs-on: ubuntu-latest
    steps:
      - name: PR title must reference Jira card
        run: |
          if [[ "${{github.event.pull_request.title}}" =~ [A-Z][A-Z0-9]+[-]{1}[0-9]{1,5} ]]; then
            echo "PR title matches Jira card."
          else
            echo "PR title doesn't match a Jira card."
            exit 1
          fi
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
        ports:
          - "5432:5432"
    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout Pull Request HEAD commit instead of the default Pull Request merge commit.
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
      - name: Run go tests
        run: |
          go install github.com/mfridman/tparse@latest 
          set -o pipefail && DIR=$PWD go test -parallel 1 ./... -json | tparse -all